### ISSUE TITLE
Issue with chat resizing

### ISSUE THREAD

**Issue by WeenieLinguine** [Ethan0429/dgg-embed#1]
Cant make chat bigger on Chrome whilst using this extension, I can only make it smaller

**Comment by Ethan0429** [comment]
@WeenieLinguine 
I'm not sure why this is the case. If I had to guess, the stream embed has the highest foreground priority, which might be overlapping with the resize bar for the chat. I might fix in the future, but a simple fix for this is just to grab the resize bar by the top/bottom where the stream does not flush against it.
